"Configures tab behavior setlocal tabstop=4
setlocal shiftwidth=4
setlocal softtabstop=4
setlocal expandtab
filetype indent on

"Maps jk and kj to Escape for faster mode switching 
imap jk <Esc>
imap kj <Esc>

let mapleader=","

"Sets white line numbers
set number
highlight LineNr ctermfg=white

"Adds indent when { + ENTER is pressed. Also closes curly brace
"inoremap {<CR> {<CR>}<C-o>O

filetype plugin on

if $COLORTERM == 'gnome-terminal'
    set t_Co=256
endif

"set background=dark
syntax enable
let g:rehash256 = 1
colorscheme molokai

nmap <C-S-P> :call <SID>SynStack()<CR>
function! <SID>SynStack()
    if !exists("*synstack")
        return
    endif
    echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc
